### ISSUE TITLE
Will the code from the book ever be in the repo?

### ISSUE THREAD

**Issue by thephet** [davidADSP/GDL_code#39]
Hi David, I am enjoying reading your book, I am around page 115.

But something that is annoying me a lot is that not all the code from the book is in the repo. For example now I wanted to copy and rewrite the GAN code, but it's nowhere to be seen, and you only show how to use the GAN class, while all the other code you showed about how to build a GAN from scratch is not part of the notebook.

It might be only my opinion, but when I am reading a programming book, I expect every bit of code to be available and tested, because that's how people learns. "Hands on machine learning" is an example of this.

Will all the code from the book be part of the notebooks?

**Comment by emres** [comment]
Hello @thephet,

I'm not @davidADSP but this got my attention (because I've recently finished the book and went through almost all of the code and examples). Which part exactly do you refer to? I was also confused in the beginning, because there's some abstraction and not every piece of code is **directly in a notebook**. The author (David) created some abstractions and helper classes, e.g. in [GAN.py](https://github.com/davidADSP/GDL_code/blob/master/models/GAN.py), but it **is** in the repository obviously. 

But maybe you're referring to some other piece of code, e.g. Keras internals? Or something else?

**Comment by thephet** [comment]
Dear @emres you are right, and I was wrong. I didn't realize the code was in that GAN.py file. I expected all of it to be in the chapter notebooks.

Sorry for this issue, I will close it, it was an error from my side.
